### ISSUE TITLE
The yellow circle will disappear in fullscreen

### ISSUE THREAD

**Issue by Jedsek** [alexeylovchikov/eye-extended-shell-extension#12]
The yellow circl will disapper in fullscreen when topbar is hidden.

set keys:
```bash
gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen "['<Super>f']"
```
then press `<Super>f`, and click eye to get yellow circle in overview
(My topbar only appears in overview)

**Comment by djinnalexio** [comment]
So, it seems like this problem is specific to Wayland. I am on Fedora 37 and had this issue until I tested the extension on x11.

On Wayland, the mouse circle is drawn behind fullscreen applications, and click coloring does not work.

**Comment by jakob30061** [comment]
> So, it seems like this problem is specific to Wayland. I am on Fedora 37 and had this issue until I tested the extension on x11.
> 
> On Wayland, the mouse circle is drawn behind fullscreen applications, and click coloring does not work.

I think this issue got resolved.
I am on Manjaro with Wayland and the mouse circle is still visible in fullscreen mode.

**Comment by alexeylovchikov** [comment]
Thank you for your help
