### ISSUE TITLE
Gnome 43 support

### ISSUE THREAD

**Issue by dorrogeray** [alexeylovchikov/eye-extended-shell-extension#16]
:pray:

**Comment by ctroncoso** [comment]
Just clone the repo, and add 44 to metadata.json
![image](https://github.com/alexeylovchikov/eye-extended-shell-extension/assets/121016/fd8e432e-67f0-49a4-9811-bc13d1d9f3eb)
Then install as instructed.

**Comment by ctroncoso** [comment]
It works, but the author should take a look at if it is a workaround or a solucion.

**Comment by alexeylovchikov** [comment]
Hi, I added support, and also added a settings popup
