### ISSUE TITLE
Click highlighting (for screencast)

### ISSUE THREAD

**Issue by ghost** [alexeylovchikov/eye-extended-shell-extension#2]
Hi Alexey,

Thank you for nice extension.

Would it be possible to add mouse click highlighting feature which is very useful for screencasts?
I see your extension has almost everything required for such feature implementation :wink: 
It would be nice to see a small colorful ripples for left, right and middle clicks with different colors.
Something like on this video: https://www.youtube.com/watch?v=INEUdtEffgE

Thanks in advance.

**Comment by alexeylovchikov** [comment]
Ok, I also thought about it

**Comment by alexeylovchikov** [comment]
Done

**Comment by ghost** [comment]
I've installed the new version of plugin with this feature.
Thanks! Works like a charm.
The only one suggestion how this feature could be enhanced, if you don't mind.
It would be nice to have a transparent mode (or "color")  for the cursor in regular state during moving, but only clicks could show the colored animation.
