### ISSUE TITLE
Mouse circle left, right and middle click don't work

### ISSUE THREAD

**Issue by mauriciovancine** [alexeylovchikov/eye-extended-shell-extension#5]
Hi Alex,

Thank you very much for the extension.

However, highlighting the left, right and middle mouse click does not work on Ubuntu 20.04. Is it just for me?

Thank you again.

**Comment by alexeylovchikov** [comment]
Check it from github

**Comment by machitgarha** [comment]
It does not work for me, either. I'm on Fedora 35, Gnome Wayland. Perhaps this issue should be re-opened?
